---

name: Test
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make-helpers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: php_tests_worktree
        run: ./test/php_tests_worktree.sh
      - name: ssm
        run: ./test/ssm.sh
